name: Deploy Snowstorm-Lite to Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy-snowstorm:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      PROJECT_ID: 'lean-ehr'
      REGION: 'europe-west1'
      SERVICE_NAME: 'snowstorm-lite-service'
      ARTIFACT_REPO: 'lean-ehr-repo'
      SNOWSTORM_PORT: '8080' # Default port for Snowstorm-Lite
      BUCKET_NAME: 'lean-ehr-loinc-data-7776' # For downloading RF2 from GCS
      RF2_PREFIX: 'snomed-packages/' # For downloading RF2 from GCS
      RF2_FILENAME: 'uk_sct2cl_41.0.0_20250924000001Z.zip' # For downloading RF2 from GCS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth # Added id to retrieve credentials_file_path and access_token
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/31765765651/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'assisted-living-app@lean-ehr.iam.gserviceaccount.com'
          create_credentials_file: true # Added to create a temp file for docker build --secret

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Submit Build to Cloud Build
        run: |
          gcloud builds submit \
            --config cloudbuild.yaml \
            --substitutions=_REGION="${{ env.REGION }}",_ARTIFACT_REPO="${{ env.ARTIFACT_REPO }}",_SERVICE_NAME="${{ env.SERVICE_NAME }}",_BUCKET_NAME="${{ env.BUCKET_NAME }}",_RF2_PREFIX="${{ env.RF2_PREFIX }}",_RF2_FILENAME="${{ env.RF2_FILENAME }}",COMMIT_SHA="${{ github.sha }}" \
            .
